### ISSUE TITLE
Title search

### ISSUE THREAD

**Issue by ayanleahmed** [patelhalley/RxAnalysis#1]
when you are searching prescription name and you enter the first letter of the drug name it should display any drug name that starts the letter "K" on the drop down. Please see the attach image.

![fda](https://cloud.githubusercontent.com/assets/13106102/8414239/a2a49ec4-1e64-11e5-9db7-ba6ca35c5d10.png)

**Comment by patelhalley** [comment]
Fixed and pushed. Please Verify

**Comment by ayanleahmed** [comment]
I was able to verify everything looks good.
